[package]
name = "simplydmx-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.74"
async-std = { version = "1.10.0", features = ["attributes"] }
simplydmx_plugin_framework = { path = "../simplydmx_plugin_framework" }

[features]
default = [
	"stdout-logging",
]

stdout-logging = []
