[package]
name = "simplydmx-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.136"
serde_json = "1.0.74"
async-std = { version = "1.10.0", features = ["attributes"] }
simplydmx_plugin_framework = { path = "../simplydmx_plugin_framework" }
sacn = { version = "0.4.3", optional = true }
uuid = "0.8.2"
async-trait = "0.1.53"

[features]
default = [
	"stdout-logging",
	"output-dmx-e131",
]

stdout-logging = []
output-dmx-e131 = [
	"sacn"
]
