[package]
name = "simplydmx_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.10.0"
rustc-hash = "2.0.0"
serde = { version = "1.0.210", features = ["derive"] }
smartstring = { version = "1.0.1", features = ["serde"] }
thiserror = "1.0.64"
uuid = { version = "1.10.0", features = ["fast-rng", "serde", "v4"] }

[lib]
path = "src/lib.rs"
