[package]
name = "simplydmx_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.136"
serde_json = "1.0.74"
async-std = { version = "1.10.0" }
simplydmx_plugin_framework = { path = "../simplydmx_plugin_framework" }
sacn = { version = "0.4.4", optional = true }
uuid = { version = "1.0.0", features = ["v4", "serde"] }
async-trait = "0.1.57"
ciborium = "0.2.0"
futures = "0.3.23"
tsify = { version = "0.4.2", default-features = false, optional = true }
linkme = { version = "0.3.5", optional = true }
anyhow = "1.0.68"
thiserror = "1.0.38"

[lib]
path = "src/lib.rs"

[[bin]]
name = "simplydmx_rpcgen"
path = "src/main.rs"
required-features = ["export-services"]

[features]
default = ["default-plugins"]

tokio1 = ["async-std/tokio1"]

# This is meant to be run stand-alone, similar to tests. It generates the rpc.ts file that the frontend runs on
export-services = ["linkme", "tsify", "simplydmx_plugin_framework/tsify", "stdout-logging", "default-plugins"]

default-plugins = ["output-dmx-e131", "blender", "api"]

stdout-logging = [] # Log service in core

output-dmx = []
output-dmx-e131 = ["output-dmx", "sacn"]

blender = []
blender-benchmark = ["blender"]

startup-benchmark = []

api = []
